// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbS8QSLMscpw-AhOkr5VHQimbXMvzcBeM',
    appId: '1:318546891134:web:2d4de661dee07ea0afa32f',
    messagingSenderId: '318546891134',
    projectId: 'cartify-43ca0',
    authDomain: 'cartify-43ca0.firebaseapp.com',
    storageBucket: 'cartify-43ca0.firebasestorage.app',
    measurementId: 'G-DBDQPRL9BX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh6VksREUJsX1Sg_6e8uJufkgT8jT9oZo',
    appId: '1:318546891134:android:c30d7488fa148a2dafa32f',
    messagingSenderId: '318546891134',
    projectId: 'cartify-43ca0',
    storageBucket: 'cartify-43ca0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrD6RuV2gHFg6k5cG1x7XfpR9cVTxIdAc',
    appId: '1:318546891134:ios:1e144374e6c84e26afa32f',
    messagingSenderId: '318546891134',
    projectId: 'cartify-43ca0',
    storageBucket: 'cartify-43ca0.firebasestorage.app',
    iosBundleId: 'com.example.cartify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrD6RuV2gHFg6k5cG1x7XfpR9cVTxIdAc',
    appId: '1:318546891134:ios:1e144374e6c84e26afa32f',
    messagingSenderId: '318546891134',
    projectId: 'cartify-43ca0',
    storageBucket: 'cartify-43ca0.firebasestorage.app',
    iosBundleId: 'com.example.cartify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbS8QSLMscpw-AhOkr5VHQimbXMvzcBeM',
    appId: '1:318546891134:web:6914960ec17ee282afa32f',
    messagingSenderId: '318546891134',
    projectId: 'cartify-43ca0',
    authDomain: 'cartify-43ca0.firebaseapp.com',
    storageBucket: 'cartify-43ca0.firebasestorage.app',
    measurementId: 'G-M6GDKCRQXL',
  );
}
